/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    copy: typeof import('./src/components/test copy.vue')['default']
    Library: typeof import('./src/components/library/index.vue')['default']
    Preview: typeof import('./src/components/preview.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Setting: typeof import('./src/components/setting.vue')['default']
    Test: typeof import('./src/components/test.vue')['default']
    Types: typeof import('./src/components/library/types/index.vue')['default']
  }
}
